import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/about">About</Link>
        </li>
        <li>
          <Link to="/servicesgrid">ServicesGrid</Link>
        </li>
        <li>
          <Link to="/servicesdetail">ServicesDetail</Link>
        </li>
        <li>
          <Link to="/projectsgrid">ProjectsGrid</Link>
        </li>
        <li>
          <Link to="/projectsdetail">ProjectsDetail</Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
